version: "3.8"
services:
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass 123
    ports:
      - "6379:6379"
  backend:
    image: docker.io/library/logistic_service:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_REDIS_HOST=redis